In [204]:
!pip install numpy


In [138]:
import numpy as np

In [139]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [140]:
a[4]

5

In [141]:
import sys
l=range(1000)
sys.getsizeof(1)*len(l)

28000

In [142]:
a= np.arange(1000)
a.itemsize * a.size

4000

In [143]:
import time
size = 1000000
l1 = range(size)
l2 = range(size)
start = time.time()
output = [(x+y) for x,y in zip(l1,l2)]
print("python list: ", (time.time()-start)*1000)

python list:  204.60891723632812


In [144]:
a1 = np.arange(size)
a2 = np.arange(size)
start = time.time()
print("Numpy: ", (time.time()-start)*1000)

Numpy:  0.0


In [145]:
b = np.array([1,2,3,4,5,6])

In [146]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [147]:
c.ndim

2

In [148]:
b.ndim

1

In [149]:
d = np.array([[1,2,6],[4,5,6],[9,8,7]])
d

array([[1, 2, 6],
       [4, 5, 6],
       [9, 8, 7]])

In [150]:
d.ndim

2

In [151]:
f = np.zeros((3,3))
f

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [152]:
h = np.zeros((6,7))
h

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [153]:
s = h.reshape(7,6)
s

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [154]:
s.shape

(7, 6)

In [155]:
s.size

42

In [156]:
s.itemsize
h = np.zeros((6,7),dtype=int)
h

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [157]:
h = np.zeros((6,7),dtype=str)
h

array([['', '', '', '', '', '', ''],
       ['', '', '', '', '', '', ''],
       ['', '', '', '', '', '', ''],
       ['', '', '', '', '', '', ''],
       ['', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '']], dtype='<U1')

In [158]:
h.dtype

dtype('<U1')

In [159]:
a.dtype

dtype('int32')

In [160]:
t = np.ones((5,8))
t

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [161]:
t = np.ones((4,7),dtype=int)
t

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])

In [162]:
d = np.arange(0,50)
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [163]:
g = np.arange(9,20)
g

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [164]:
g = np.arange(9,20,2)
g

array([ 9, 11, 13, 15, 17, 19])

In [165]:
j = np.linspace(0,5,3)
j

array([0. , 2.5, 5. ])

In [166]:
j = np.linspace(0,5,2)
j

array([0., 5.])

In [167]:
j = np.linspace(0,50,5)
j

array([ 0. , 12.5, 25. , 37.5, 50. ])

In [168]:
j = np.linspace(0,5,5)
j

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [169]:
c = np.array([[1,2],[3,4],[5,6]])
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [170]:
c.shape

(3, 2)

In [171]:
c.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [172]:
c.ravel()

array([1, 2, 3, 4, 5, 6])

In [173]:
c.max()

6

In [174]:
c.min()

1

In [175]:
c.mean()

3.5

In [176]:
c.sum()

21

In [177]:
c.sum(axis=1)

array([ 3,  7, 11])

In [178]:
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [179]:
c.sum(axis=0)

array([ 9, 12])

In [180]:
b = np.array([[1,4],[9,16]])
b

array([[ 1,  4],
       [ 9, 16]])

In [181]:
np.sqrt(b)

array([[1., 2.],
       [3., 4.]])

In [182]:
np.mean(b)

7.5

In [183]:
np.std(b)

5.678908345800274

In [184]:
a = np.array([[4,1],[16,9]])
a

array([[ 4,  1],
       [16,  9]])

In [185]:
a+b

array([[ 5,  5],
       [25, 25]])

In [186]:
a*b

array([[  4,   4],
       [144, 144]])

In [187]:
np.dot(a,b)

array([[ 13,  32],
       [ 97, 208]])

In [188]:
import os
os.getcwd()


'C:\\Users\\hossin'

In [189]:
a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [190]:
for item in a:
    print(item)

[1 2]
[3 4]
[5 6]


In [191]:
for item in a.flat:
    print(item)

1
2
3
4
5
6


In [192]:
a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [193]:
b = np.arange(8,14).reshape(3,2)
b

array([[ 8,  9],
       [10, 11],
       [12, 13]])

In [194]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 8,  9],
       [10, 11],
       [12, 13]])

In [195]:
np.hstack((a,b))

array([[ 0,  1,  8,  9],
       [ 2,  3, 10, 11],
       [ 4,  5, 12, 13]])

In [196]:
c = np.arange(40).reshape(4,10)
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [197]:
np.hsplit(c,5)

[array([[ 0,  1],
        [10, 11],
        [20, 21],
        [30, 31]]), array([[ 2,  3],
        [12, 13],
        [22, 23],
        [32, 33]]), array([[ 4,  5],
        [14, 15],
        [24, 25],
        [34, 35]]), array([[ 6,  7],
        [16, 17],
        [26, 27],
        [36, 37]]), array([[ 8,  9],
        [18, 19],
        [28, 29],
        [38, 39]])]

In [198]:
np.vsplit(c,4)

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29]]),
 array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])]

In [199]:
f = np.arange(12).reshape(3,4)
f

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [200]:
b = f > 4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [201]:
f.dtype

dtype('int32')

In [202]:
f[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [203]:
f[b] = 0
f

array([[0, 1, 2, 3],
       [4, 0, 0, 0],
       [0, 0, 0, 0]])